version: "3"
services:
    pgsql:
        build: pgsql
        container_name: pgsql
        environment:
            - POSTGRES_USER=${ENV_POSTGRES_USER}
            - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}
            - POSTGRES_DB=${ENV_POSTGRES_DB}
            - POSTGRES_HOST_AUTH_METHOD=trust
        restart: always
        networks:
            - best_network
        ports:
            - 5432:5432
    front:
        build: front
        container_name: front
        restart: always
        ports:
            - 3001:3001
        networks:
            - best_network
        depends_on:
            - back
        volumes:
            - ./front:/app
            - /app/node_modules
    back:
        build: back
        container_name: back
        ports:
            - 3000:3000
        restart: always
        networks:
            - best_network
        depends_on:
            - pgsql
        links:
            - pgsql
        volumes:
            - ./back:/app
            - /app/node_modules
networks:
    best_network:
        driver: bridge
