version: "3"
services:
    postgres:
        build: pgsql
        container_name: ad_postgres
        env_file:
            - ./back/.env
        restart: always
        networks:
            - ad_network
        ports:
            - 5432:5432
    front:
        build: front
        container_name: ad_front
        restart: always
        ports:
            - 3001:3001
        networks:
            - ad_network
        depends_on:
            - back
        volumes:
            - ./front:/app
            - /app/node_modules
    back:
        build: back
        container_name: ad_back
        ports:
            - 3000:3000
        restart: always
        networks:
            - ad_network
        depends_on:
            - postgres
        links:
            - ad_postgres
        volumes:
            - ./back:/app
            - /app/node_modules
    #pgadmin:
    #    image: dpage/pgadmin4
    #    restart: always
    #    container_name: ad_pgadmin4
    #    environment:
    #        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    #        - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    #    ports:
    #        - "5050:80"
    #    depends_on:
    #        - db
networks:
    ad_network:
        driver: bridge
# done :
#export DOCKER_BUILDKIT=0
#export COMPOSE_DOCKER_CLI_BUILD=0
