version: "3"
services:
    ad-postgres:
        build: pgsql
        container_name: ad-postgres
        env_file:
            - ./back/.env
        restart: always
        networks:
            - ad-network
        ports:
            - 5432:5432

    ad-front:
        build: front
        container_name: ad-front
        restart: always
        ports:
            - 3003:3003
        networks:
            - ad-network
        depends_on:
            - ad-back
        volumes:
            - ./front:/app
            - /app/node_modules

    ad-back:
        build: back
        container_name: ad-back
        ports:
            - 3002:3002
        restart: always
        networks:
            - ad-network
        depends_on:
            - ad-postgres
        links:
            - ad-postgres
        volumes:
            - ./back:/app
            - /app/node_modules

networks:
    ad-network:
        driver: bridge
# done :
#export DOCKER_BUILDKIT=0
#export COMPOSE_DOCKER_CLI_BUILD=0
